name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git for private repos
        run: git config --global url."https://x-access-token:${{ secrets.PAT_FOR_PRIVATE_REPOS }}@github.com/".insteadOf "https://github.com/"
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Test
        run: uv run pytest
